# Parameters for open_loop_intersection_node
# #Turn right through intersection
turn_left: #time, velocity, angular vel
  - [0.8, 0.43, 0]
  - [2.2, 0.43, 2.696]
#  - [0.1, 0.0, 0.0]
  - [0.1, 0.43, 0.0]
turn_right:
  - [0.8, 0.43, 0]
  - [1.25, 0.43, -3.606]
#  - [0.1, 0.0, 0.0]
  - [0.1, 0.3, 0.0]
turn_forward:
  - [1.0, 0.43, 1.29]
  - [1.0, 0.43, -0.86]
  - [0.5, 0.3, 0.0]
# turn_stop:
#   - [0.2, 0.0, 0.0]

#do we want to update the values based on where/what angle we stop at.
trajectory_reparam: 0