img_size: [120,160]
top_cutoff: 40

detector: 
  - color_line_detector.LineDetectorHSV
  - configuration:
      dilation_kernel_size: 3
      canny_thresholds: [60,150]
      hough_threshold: 20
      hough_min_line_length: 3
      hough_max_line_gap:    1

     
      hsv_white1:  [0,0,150]
      hsv_white2:  [180,60,255]
      hsv_yellow1: [25,140,100]
      hsv_yellow2: [45,255,255]
      hsv_red1:    [0,140,100]
      hsv_red2:    [15,255,255]
      hsv_red3:    [165,140,100]
      hsv_red4:    [180,255,255]
      hsv_green1:    [70,100,60]
      hsv_green2:    [90,255,255]  
      hsv_blue1:    [90,80,50]
      hsv_blue2:    [110,255,255]    
      hsv_no1:    [0,0,0]
      hsv_no2:    [0,0,0]    
