img_size: [240,320]
top_cutoff: 90
dilation_kernel_size: 3
canny_thresholds: [50,150]
hough_threshold: 20
hough_min_line_length: 3
hough_max_line_gap:    1


hsv_white1:  [0,0,50]
hsv_white2:  [255,120,255]
hsv_yellow1: [25,210,50]
hsv_yellow2: [45,255,255]
hsv_red1:    [0,200,50]
hsv_red2:    [15,255,255]
hsv_red3:    [240,200,50]
hsv_red4:    [255,255,255]
