  # default parameters for forward_kinematics_node and inverse_kinematics_node
  K_l:          28.6
  K_r:          25.9
  radius_l:     0.02
  radius_r:     0.02
  baseline_lr:  0.217
  fi_theta_dot_function: Duty_fi_theta_dot_naive
  fi_v_function: Duty_fi_v_naive
  theta_dot_weights: [-1.0]
  v_weights: [1.0]
